---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: cryoem-daq-dev--dags
  labels:
    type: local
spec:
  storageClassName: cryoem-daq-dev--dags
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  local:
    path: /sdf/group/cryoem/dev/daq/airflow/dags
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: storage/cryoem
          operator: In
          values:
          - 'true'
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: cryoem-daq-dev--dags
spec:
  storageClassName: cryoem-daq-dev--dags
  accessModes:
    - "ReadWriteMany"
  resources:
    requests:
      storage: 1Gi
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: cryoem-daq-dev--sdf-dags
  labels:
    type: local
spec:
  storageClassName: cryoem-daq-dev--sdf-dags
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  local:
    path: /sdf/group/cryoem/dev/daq/airflow/dags
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: storage/sdf
          operator: In
          values:
          - 'true'
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: cryoem-daq-dev--sdf-dags
spec:
  storageClassName: cryoem-daq-dev--sdf-dags
  accessModes:
    - "ReadWriteMany"
  resources:
    requests:
      storage: 1Gi

---

kind: PersistentVolume
apiVersion: v1
metadata:
  name: cryoem-daq-dev--plugins
  labels:
    type: local
spec:
  storageClassName: cryoem-daq-dev--plugins
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  local:
    path: /sdf/group/cryoem/dev/daq/airflow/plugins
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: storage/cryoem
          operator: In
          values:
          - 'true'
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: cryoem-daq-dev--plugins
spec:
  storageClassName: cryoem-daq-dev--plugins
  accessModes:
    - "ReadWriteMany"
  resources:
    requests:
      storage: 1Gi
---

kind: PersistentVolume
apiVersion: v1
metadata:
  name: cryoem-daq-dev--sdf-plugins
  labels:
    type: local
spec:
  storageClassName: cryoem-daq-dev--sdf-plugins
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  local:
    path: /sdf/group/cryoem/dev/daq/airflow/plugins
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: storage/sdf
          operator: In
          values:
          - 'true'
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: cryoem-daq-dev--sdf-plugins
spec:
  storageClassName: cryoem-daq-dev--sdf-plugins
  accessModes:
    - "ReadWriteMany"
  resources:
    requests:
      storage: 1Gi

---

kind: PersistentVolume
apiVersion: v1
metadata:
  name: cryoem-daq-dev--logs
  labels:
    type: local
spec:
  storageClassName: cryoem-daq-dev--logs
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  local:
    path: /sdf/group/cryoem/dev/daq/airflow/logs
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: storage/cryoem
          operator: In
          values:
          - 'true'
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: cryoem-daq-dev--logs
spec:
  storageClassName: cryoem-daq-dev--logs
  accessModes:
    - "ReadWriteMany"
  resources:
    requests:
      storage: 1Gi

---

kind: PersistentVolume
apiVersion: v1
metadata:
  name: cryoem-daq-dev--sdf-logs
  labels:
    type: local
spec:
  storageClassName: cryoem-daq-dev--sdf-logs
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  local:
    path: /sdf/group/cryoem/dev/daq/airflow/logs
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: storage/sdf
          operator: In
          values:
          - 'true'
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: cryoem-daq-dev--sdf-logs
spec:
  storageClassName: cryoem-daq-dev--sdf-logs
  accessModes:
    - "ReadWriteMany"
  resources:
    requests:
      storage: 1Gi

