---

kind: PersistentVolume
apiVersion: v1
metadata:
  name: cryoem-daq-dev--redis-0
  labels:
    type: local
spec:
  storageClassName: cryoem-daq-dev--redis
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  local:
    path: /sdf/group/cryoem/dev/daq/redis/
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: storage/cryoem
          operator: In
          values:
          - 'true'

---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: cryoem-daq-dev--sdf-redis-0
  labels:
    type: local
spec:
  storageClassName: cryoem-daq-dev--sdf-redis
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  local:
    path: /sdf/group/cryoem/dev/daq/redis/
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: storage/sdf
          operator: In
          values:
          - 'true'
