
apiVersion: v1
kind: Service
metadata:
  name: redis
  annotations:
    metallb.universe.tf/address-pool: internal
    metallb.universe.tf/allow-shared-ip: cryoem-daq-dev
  labels:
    app: redis
spec:
  ports:
  - port: 6379
    name: redis
  selector:
    role: messagebus
  type: LoadBalancer

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-primary
spec:
  serviceName: redis-primary
  selector:
    matchLabels:
      role: messagebus
  replicas: 1
  template:
    metadata:
      labels:
        role: messagebus
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: redis-primary
        image: redis:4.0.14-alpine
        imagePullPolicy: Always
        ports:
        - containerPort: 6379
          name: redis-primary
        volumeMounts:
        - name: redis-data
          mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: redis-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: cryoem-daq-prod--redis
      #storageClassName: cryoem-daq-dev--redis
      resources:
        requests:
          storage: 5Gi

